from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


BRAND_NAVY = colors.HexColor("#0B1026")
BRAND_CYAN = colors.HexColor("#06B6D4")
BRAND_PURPLE = colors.HexColor("#6366F1")
MUTED = colors.HexColor("#526078")


def _value(record, key, default="-"):
    value = record.get(key)
    return default if value in (None, "") else value


def _format_timestamp(value):
    if not value:
        return "-"
    try:
        parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        return parsed.strftime("%d %b %Y %I:%M %p")
    except ValueError:
        return str(value)


def _date_and_time(value):
    formatted = _format_timestamp(value)
    parts = formatted.split(" ")
    if len(parts) >= 5:
        return " ".join(parts[:3]), " ".join(parts[3:])
    return formatted, "-"


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor("#D8E0EE"))
    canvas.line(18 * mm, 14 * mm, A4[0] - 18 * mm, 14 * mm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    generated = datetime.now().strftime("%d %b %Y %I:%M %p")
    canvas.drawString(18 * mm, 9 * mm, f"Generated by Snap AI Attendance | {generated}")
    canvas.drawRightString(A4[0] - 18 * mm, 9 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _info_table(items, styles):
    rows = []
    for label, value in items:
        rows.append([Paragraph(f"<b>{label}</b>", styles["label"]), Paragraph(str(value), styles["body"])])
    table = Table(rows, colWidths=[36 * mm, 135 * mm], hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F1F5FB")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D8E0EE")),
        ("INNERGRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#E3E9F2")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return table


def generate_attendance_pdf(session_id, teacher, subject, records, unknown_faces=0):
    """Return a branded, multi-page PDF for one attendance session in memory."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=20 * mm,
        title="Snap AI Attendance Report",
        author="Snap AI Attendance",
    )
    base = getSampleStyleSheet()
    styles = {
        "brand": ParagraphStyle("brand", parent=base["Title"], fontName="Helvetica-Bold", fontSize=18, textColor=BRAND_NAVY, spaceAfter=2),
        "title": ParagraphStyle("title", parent=base["Heading1"], fontName="Helvetica-Bold", fontSize=16, textColor=BRAND_PURPLE, alignment=TA_LEFT, spaceAfter=8),
        "section": ParagraphStyle("section", parent=base["Heading2"], fontName="Helvetica-Bold", fontSize=10, textColor=BRAND_NAVY, spaceBefore=10, spaceAfter=5),
        "body": ParagraphStyle("body", parent=base["BodyText"], fontName="Helvetica", fontSize=8.5, leading=11, textColor=BRAND_NAVY),
        "label": ParagraphStyle("label", parent=base["BodyText"], fontName="Helvetica-Bold", fontSize=8.5, leading=11, textColor=MUTED),
        "small": ParagraphStyle("small", parent=base["BodyText"], fontName="Helvetica", fontSize=8, leading=10, textColor=MUTED),
        "center": ParagraphStyle("center", parent=base["BodyText"], fontName="Helvetica", fontSize=8, leading=10, alignment=TA_CENTER),
    }

    present = sum(1 for row in records if row.get("is_present"))
    total = len(records)
    absent = max(total - present, 0)
    percentage = (present / total * 100) if total else 0
    subject = subject or {}
    teacher = teacher or {}
    timestamp = session_id
    attendance_date, attendance_time = _date_and_time(timestamp)

    story = [
        Paragraph("SNAP <font color='#06B6D4'>AI</font> ATTENDANCE", styles["brand"]),
        Paragraph("AI Generated Attendance Report", styles["title"]),
        Paragraph("Smart attendance powered by face and voice recognition", styles["small"]),
        Spacer(1, 5 * mm),
        Paragraph("Session Details", styles["section"]),
        _info_table([
            ("Teacher", _value(teacher, "name")),
            ("Teacher ID / Email", _value(teacher, "email", _value(teacher, "username"))),
            ("Subject", _value(subject, "name")),
            ("Subject Code", _value(subject, "subject_code")),
            ("Section / Batch", _value(subject, "section")),
            ("Attendance Date", attendance_date),
            ("Attendance Time", attendance_time),
            ("Session ID", timestamp),
        ], styles),
        Paragraph("Attendance Summary", styles["section"]),
    ]

    summary = Table([
        [Paragraph("TOTAL STUDENTS", styles["center"]), Paragraph("PRESENT", styles["center"]), Paragraph("ABSENT", styles["center"]), Paragraph("UNKNOWN FACES", styles["center"]), Paragraph("ATTENDANCE", styles["center"])],
        [Paragraph(f"<b>{total}</b>", styles["center"]), Paragraph(f"<b>{present}</b>", styles["center"]), Paragraph(f"<b>{absent}</b>", styles["center"]), Paragraph(f"<b>{unknown_faces}</b>", styles["center"]), Paragraph(f"<b>{percentage:.1f}%</b>", styles["center"])],
    ], colWidths=[34 * mm] * 5)
    summary.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_NAVY), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#F1F5FB")), ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#D8E0EE")),
        ("INNERGRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D8E0EE")), ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 7), ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))
    story.extend([summary, Paragraph("Student Attendance", styles["section"])])

    table_rows = [[Paragraph("No.", styles["center"]), Paragraph("Student Name", styles["center"]), Paragraph("Student ID", styles["center"]), Paragraph("Status", styles["center"]), Paragraph("Recognition", styles["center"])]]
    for index, row in enumerate(records, 1):
        status = "PRESENT" if row.get("is_present") else "ABSENT"
        table_rows.append([str(index), _value(row.get("students") or row, "name"), str(_value(row.get("students") or row, "student_id", row.get("student_id", "-"))), status, _value(row, "confidence")])
    attendance_table = Table(table_rows, colWidths=[12 * mm, 70 * mm, 28 * mm, 28 * mm, 33 * mm], repeatRows=1)
    attendance_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_PURPLE), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D8E0EE")), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7F9FC")]),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(attendance_table)
    if unknown_faces:
        story.extend([Spacer(1, 4 * mm), Paragraph(f"Unknown faces detected separately: {unknown_faces}", styles["small"])])
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    buffer.seek(0)
    return buffer
